### PR TITLE
Fix links in README.md

### PR DESCRIPTION
**Pull request by gwenzek**
links to matlab examples, to the latest jar and to the javadoc

### CODE REVIEW

**Comment by henryadams** [comment]
Hi all,
My understanding is that the links in README.md
https://github.com/appliedtopology/javaplex/blob/master/README.md
are up-to-date. Indeed, the link to the "latest release" is now free of version numbers. However, the links on the frontpage at
http://appliedtopology.github.io/javaplex/
are not up-to-date. I could not figure out how to edit the frontpage. Any advice how to do this?
Best, Henry

**Comment by ogdet** [comment]
Hi Henry,

The project page is hosted on the "gh-pages" branch of the repository. The
simplest way of editing it is to go to "Settings" on the right-hand side of
the page, and then select "Automatic Page Generator". Just paste in the
contents of the readme, and make sure that the style does not change.  Let
me know if there are further questions.

Andrew

**Comment by henryadams** [comment]
Hi Andrew,

Great, thanks! I found the "gh-pages" branch. I couldn't find the "settings" button or "automatic page generator", but I just went to the file
https://github.com/appliedtopology/javaplex/blob/gh-pages/index.html
and edited there. So the frontpage is now in-sync with the README.md file. I've also added this to my list of things to do with each new release I make.

(I'm not sure how to close this "issues" thread, but I think it's now ready to be closed.)

Thanks, Henry

**Comment by michiexile** [comment]
The formal issue was actually closed back when I merged the pull request. We don’t need to do anything more to it.

// Mikael

**Pull request merged**
